import { useEffect } from 'react'

const mark = <svg className="mark" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><g transform="rotate(-30 12 12)"><circle cx="7.3" cy="3.2" r="1.45"/><rect x="5.5" y="4.7" width="3.6" height="14.6" rx="1.8"/><rect x="14.9" y="4.7" width="3.6" height="14.6" rx="1.8"/><circle cx="16.7" cy="20.8" r="1.45"/></g></svg>
const sparkle = <svg className="sparkle" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2.6C12.55 2.6 12.88 3.15 13.08 4.7c.62 4.7 1.52 5.6 6.22 6.22 1.55.2 2.1.53 2.1 1.08s-.55.88-2.1 1.08c-4.7.62-5.6 1.52-6.22 6.22-.2 1.55-.53 2.1-1.08 2.1s-.88-.55-1.08-2.1c-.62-4.7-1.52-5.6-6.22-6.22C3.15 12.88 2.6 12.55 2.6 12s.55-.88 2.1-1.08c4.7-.62 5.6-1.52 6.22-6.22C11.12 3.15 11.45 2.6 12 2.6Z"/></svg>
const workflow = <svg viewBox="0 0 24 24" aria-hidden="true"><defs><linearGradient id="a" x1="3" y1="2" x2="14" y2="22"><stop stopColor="#fff" stopOpacity=".38"/><stop offset="1" stopColor="#3a3a3a" stopOpacity=".62"/></linearGradient><linearGradient id="b" x1="14" y1="2" x2="3" y2="22"><stop stopColor="#3a3a3a" stopOpacity=".38"/><stop offset="1" stopColor="#fff" stopOpacity=".62"/></linearGradient></defs><rect x="3.4" y="2.6" width="7.2" height="18.8" rx="3.6" fill="url(#a)"/><rect x="13.4" y="2.6" width="7.2" height="18.8" rx="3.6" fill="url(#b)"/><rect x="9.2" y="10.9" width="5.6" height="2.2" rx="1.1" fill="#4a4a4a"/></svg>
const download = <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="2.4" y="2.4" width="19.2" height="19.2" rx="6.2" fill="#fff"/><path d="M12 7.1v7.4M8.15 12.35 12 16.2l3.85-3.85" stroke="#111" strokeWidth="1.85" strokeLinecap="round" strokeLinejoin="round"/></svg>
const teams = <svg viewBox="0 0 40 22" aria-hidden="true"><circle cx="10.2" cy="11" r="9.2" fill="#2b2b2b"/><ellipse cx="10.2" cy="12.1" rx="4.15" ry="3.7" fill="#f4f4f4"/><circle cx="8.7" cy="11.5" r=".7"/><circle cx="11.7" cy="11.5" r=".7"/><circle cx="20.2" cy="11" r="9.2" fill="#fff"/><circle cx="17.5" cy="10" r="1.7" fill="#111"/><circle cx="22.9" cy="10" r="1.7" fill="#111"/><path d="M17.3 14c1.8 1.3 3.8 1.3 5.7 0" stroke="#111" strokeWidth="1.2" fill="none"/><circle cx="30.2" cy="11" r="9.2" fill="#f26b1d"/><text x="30.2" y="15.1" textAnchor="middle" fontSize="12.5" fontWeight="700" fill="#fff">e</text></svg>

export default function App() {
  useEffect(() => { const body=document.body; const burger=document.querySelector<HTMLButtonElement>('.burger'); const nav=document.querySelector('#site-nav'); const close=()=>{body.classList.remove('menu-open');burger?.setAttribute('aria-expanded','false');burger?.setAttribute('aria-label','Open menu')}; burger?.addEventListener('click',()=>{const open=!body.classList.contains('menu-open');body.classList.toggle('menu-open',open);burger.setAttribute('aria-expanded',String(open));burger.setAttribute('aria-label',open?'Close menu':'Open menu')}); nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',close)); const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close()}; const resize=()=>{if(innerWidth>=901)close()}; addEventListener('keydown',key);addEventListener('resize',resize); const all=[...document.querySelectorAll<HTMLElement>('.appear'),document.querySelector<HTMLElement>('.hero-photo')].filter(Boolean) as HTMLElement[]; const end=(e:Event)=>e.currentTarget instanceof HTMLElement&&e.currentTarget.classList.add('is-in'); all.forEach(el=>el.addEventListener('animationend',end,{once:true})); requestAnimationFrame(()=>requestAnimationFrame(()=>all.forEach(el=>{if(el.getAnimations().every(a=>a.playState!=='running'&&a.playState!=='finished'))el.classList.add('is-in')}))); return()=>{close();removeEventListener('keydown',key);removeEventListener('resize',resize);all.forEach(el=>el.removeEventListener('animationend',end))} },[])
  return <><div className="grain"/><video className="hero-photo" autoPlay muted loop playsInline src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260818_072341_50851634-bbc3-4c33-9acc-7647d4db44aa.mp4"/><div className="page"><div className="menu-backdrop"/><header className="header"><a className="logo appear appear--scale" href="#top" aria-label="Vesper.ai">{mark}<span>Vesper<span className="logo-suffix">.ai</span></span></a><nav id="site-nav" aria-label="Primary"><a className="appear appear--scale" href="#benefits">Benefits</a><a className="appear appear--soft" href="#how-it-works">How It Works</a><a className="appear appear--scale" href="#faqs">FAQs</a><a className="appear appear--soft" href="#pricing">Pricing</a></nav><a className="btn btn-solid header-cta appear appear--scale" href="#start">Start for Free</a><button className="burger appear appear--scale" aria-controls="site-nav" aria-expanded="false" aria-label="Open menu"><i/><i/><i/></button></header><main className="hero" id="top"><div className="hero-copy"><span className="badge appear appear--pop">{sparkle}<span>Operational AI Infrastructure</span></span><h1><span className="headline-line appear appear--mask">Train <em>AI agents</em> on your</span><span className="headline-line appear appear--mask">workflows in minutes.</span></h1><p className="lede appear appear--soft">Deploy adaptive AI agents that learn, execute, and scale operational tasks across your business.</p><div className="hero-actions"><a className="btn btn-solid appear appear--btn" href="#start">Start for Free</a><a className="btn btn-ghost hero-ghost appear appear--side" href="#demo">See it in action</a></div></div></main><footer className="stats"><div className="stat appear appear--stat">{workflow}<span>4.2M+ workflows automated</span></div><div className="stat appear appear--stat">{download}<span>92% reduction in manual operations</span></div><div className="stat appear appear--stat">{teams}<span>180+ operational teams onboarded</span></div></footer></div></>
}
